controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index

login:
    path: /login
    controller: App\Controller\SecurityController::index

api_article:
    path: /api/articles
    controller: App\Controller\API\ArticleController::index

app_article_index:
    path: /articles
    controller: App\Controller\ArticleController::index